### ISSUE TITLE
Not able to authenticate 

### ISSUE THREAD

**Issue by gmalhotra02** [tasict/homebridge-jci-hitachi-platform#4]
Hi Couldn’t try this as was not able to authenticate 

not sure if it is because Hitachi in my region is having AirCloud Go as the Wi-Fi remote app. Google home connecting plugin as available. 

Can you check that ?

**Comment by tasict** [comment]
For Hitachi air conditioners, different countries have different communication protocols and apps. Therefore, the behavior of this plugin should align with that of the respective app. If you are not using this app to control your air conditioner, it means that your air conditioner's built-in control module is incompatible with this plugin.

https://apps.apple.com/app/id1359037577
