### ISSUE TITLE
 Login Error: AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by rolandpallagi** [tasict/homebridge-jci-hitachi-platform#6]
I can not get this work. what could be the rpoblem. I am runnung latest version and up to date homebridge

**Comment by tasict** [comment]
Which mobile app do you use?

**Comment by tasict** [comment]
This plugins only support model with this app
https://apps.apple.com/tw/app/%E9%9B%B2%E7%AB%AF%E6%99%BA%E6%85%A7%E6%8E%A7/id1359037577
